using System;
using System.Collections.Generic;

namespace ATKTip;

internal static partial class BossModRebornExport
{
    private static IReadOnlyDictionary<string, JobDefinition> CreateJobDefinitions()
        => new Dictionary<string, JobDefinition>(StringComparer.OrdinalIgnoreCase)
        {
            ["Astrologian"] = CreateJobDefinition(
                "AST",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassASTUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Repose", "Repose", "Use"),
                    ("Esuna", "Esuna", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Rescue", "Rescue", "Use"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("Helios", "Helios", "Use"),
                    ("Lightspeed", "Lightspeed", "Use"),
                    ("BeneficII", "BeneficII", "Use"),
                    ("EssentialDignity", "EssentialDignity", "Use"),
                    ("AspectedBenefic", "AspectedBenefic", "Use"),
                    ("Synastry", "Synastry", "Use"),
                    ("CollectiveUnconscious", "CollectiveUnconscious", "Use"),
                    ("CelestialOpposition", "CelestialOpposition", "Use"),
                    ("CelestialIntersection", "CelestialIntersection", "Use"),
                    ("NeutralSect", "NeutralSect", "Use"),
                    ("Exaltation", "Exaltation", "Use"),
                    ("SunSign", "SunSign", "Use"),
                    ("AspectedHelios", "AspectedHelios", "Use"),
                    ("HeliosConjunction", "AspectedHelios", "UseEx"),
                    ("EarthlyStar", "EarthlyStar", "Use"),
                    ("StellarDetonation", "EarthlyStar", "End"),
                    ("Horoscope", "Horoscope", "Use"),
                    ("HoroscopeEnd", "Horoscope", "End"),
                    ("Macrocosmos", "Macrocosmos", "Use"),
                    ("MicrocosmosEnd", "Macrocosmos", "End")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.AST",
                    ("Divination", "Buffs", "Force"))),

            ["Bard"] = CreateJobDefinition(
                "BRD",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassBRDUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("LegGraze", "LegGraze", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("FootGraze", "FootGraze", "Use"),
                    ("HeadGraze", "HeadGraze", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("WardensPaean", "WardensPaean", "Use"),
                    ("NaturesMinne", "NaturesMinne", "Use"),
                    ("Troubadour", "Troubadour", "Use88IfNotActive")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.BRD",
                    ("BattleVoice", "Buffs", "Force"),
                    ("RadiantFinale", "Buffs", "Force"))),

            ["Black Mage"] = CreateJobDefinition(
                "BLM",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassBLMUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Sleep", "Sleep", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Addle", "Addle", "UseEx"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("Manaward", "Manaward", "Use"),
                    ("AetherialManipulation", "Dash", "Force")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.BLM",
                    ("Scathe", "Scathe", "Allow"),
                    ("Thunder1", "DoT", "Force"),
                    ("Thunder2", "DoT", "Force"),
                    ("Thunder3", "DoT", "Force"),
                    ("Thunder4", "DoT", "Force"),
                    ("HighThunder", "DoT", "Force"),
                    ("HighThunder2", "DoT", "Force"),
                    ("LeyLines", "LL", "OpenerOnly"),
                    ("Retrace", "LL", "Delay"),
                    ("BetweenTheLines", "LL", "Force"),
                    ("Triplecast", "TC", "Force"),
                    ("Manafont", "Manafont", "Force"))),

            ["Blue Mage"] = CreateJobDefinition(
                "BLU",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassBLUUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Sleep", "Sleep", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Addle", "Addle", "UseEx"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("Bristle", "Bristle", "Use"),
                    ("WhiteWind", "White Wind", "Use"),
                    ("IceSpikes", "Ice Spikes", "Use"),
                    ("OffGuard", "Off Guard", "Use"),
                    ("Transfusion", "Transfusion", "Use"),
                    ("Diamondback", "Diamondback", "Use"),
                    ("MightyGuard", "Mighty Guard", "Use"),
                    ("ToadOil", "Toad Oil", "Use"),
                    ("MoonFlute", "Moon Flute", "Use"),
                    ("PeculiarLight", "Peculiar Light", "Use"),
                    ("VeilOfTheWhorl", "Veil Of The Whorl", "Use"),
                    ("EerieSoundwave", "Eerie Soundwave", "Use"),
                    ("PomCure", "Pom Cure", "Use"),
                    ("Gobskin", "Gobskin", "Use"),
                    ("Avail", "Avail", "Use"),
                    ("FrogLegs", "Frog Legs", "Use"),
                    ("Whistle", "Whistle", "Use"),
                    ("Cactguard", "Cactguard", "Use"),
                    ("AngelWhisper", "Angel Whisper", "Use"),
                    ("Exuviation", "Exuviation", "Use"),
                    ("ColdFog", "Cold Fog", "Use"),
                    ("Stotram", "Stotram", "Use"),
                    ("AngelsSnack", "Angels Snack", "Use"),
                    ("ChelonianGate", "Chelonian Gate", "Use"),
                    ("BasicInstinct", "Basic Instinct", "Use"),
                    ("DragonForce", "Dragon Force", "Use"),
                    ("Schiltron", "Schiltron", "Use"),
                    ("Rehydration", "Rehydration", "Use"),
                    ("ForceField", "Force Field", "Use"))),

            ["Dancer"] = CreateJobDefinition(
                "DNC",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassDNCUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("LegGraze", "LegGraze", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("FootGraze", "FootGraze", "Use"),
                    ("HeadGraze", "HeadGraze", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("CuringWaltz", "CuringWaltz", "Use"),
                    ("Improvisation", "Improvisation", "Use"),
                    ("ShieldSamba", "Shield Samba", "Use88IfNotActive")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.DNC",
                    ("TechnicalStep", "Buffs", "Force"),
                    ("SingleTechnicalFinish", "Buffs", "Force"),
                    ("DoubleTechnicalFinish", "Buffs", "Force"),
                    ("TripleTechnicalFinish", "Buffs", "Force"),
                    ("QuadrupleTechnicalFinish", "Buffs", "Force"),
                    ("SingleTechnicalFinish2", "Buffs", "Force"),
                    ("DoubleTechnicalFinish2", "Buffs", "Force"),
                    ("TripleTechnicalFinish2", "Buffs", "Force"),
                    ("QuadrupleTechnicalFinish2", "Buffs", "Force"),
                    ("ClosedPosition", "Partner", "Automatic"))),

            ["Dark Knight"] = CreateJobDefinition(
                "DRK",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassDRKUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Rampart", "Rampart", "Use"),
                    ("LowBlow", "LowBlow", "Use"),
                    ("Provoke", "Provoke", "Use"),
                    ("Interject", "Interject", "Use"),
                    ("Shirk", "Shirk", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Reprisal", "Reprisal", "UseEx"),
                    ("DarkMind", "DarkMind", "Use"),
                    ("LivingDead", "LivingDead", "Use"),
                    ("DarkMissionary", "DarkMissionary", "Use"),
                    ("ShadowWall", "ShadowWall", "ShadowWall"),
                    ("ShadowedVigil", "ShadowWall", "ShadowedVigil"),
                    ("TheBlackestNight", "TheBlackestNight", "Force"),
                    ("Oblation", "Oblation", "Force"),
                    ("Shadowstride", "Shadowstride", "GapCloseHold1")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.DRK",
                    ("LivingShadow", "Buffs", "Force"))),

            ["Dragoon"] = CreateJobDefinition(
                "DRG",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassDRGUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("WingedGlide", "Winged Glide", "GapCloseHold1")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.DRG",
                    ("BattleLitany", "Buffs", "Force"),
                    ("Jump", "HJMD", "Force"),
                    ("HighJump", "HJMD", "Force"),
                    ("MirageDive", "HJMD", "Force"),
                    ("DragonfireDive", "Dive", "Allow"),
                    ("Stardiver", "Dive", "Allow"),
                    ("LanceCharge", "LC", "Force"))),

            ["Gunbreaker"] = CreateJobDefinition(
                "GNB",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassGNBUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Rampart", "Rampart", "Use"),
                    ("LowBlow", "LowBlow", "Use"),
                    ("Provoke", "Provoke", "Use"),
                    ("Interject", "Interject", "Use"),
                    ("Shirk", "Shirk", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Reprisal", "Reprisal", "UseEx"),
                    ("Camouflage", "Camouflage", "Use"),
                    ("Nebula", "Nebula", "Use"),
                    ("Superbolide", "Superbolide", "Use"),
                    ("HeartOfLight", "HeartOfLight", "Use"),
                    ("Aurora", "Aurora", "Force"),
                    ("HeartOfStone", "HeartOfCorundum", "HeartOfStone"),
                    ("HeartOfCorundum", "HeartOfCorundum", "HeartOfCorundum"),
                    ("Trajectory", "Trajectory", "GapCloseHold1")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.GNB",
                    ("Bloodfest", "Buffs", "Force"),
                    ("NoMercy", "Buffs", "Force"))),

            ["Machinist"] = CreateJobDefinition(
                "MCH",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassMCHUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("LegGraze", "LegGraze", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("FootGraze", "FootGraze", "Use"),
                    ("HeadGraze", "HeadGraze", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Dismantle", "Dismantle", "Use"),
                    ("Tactician", "Tactician", "Use88IfNotActive")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.MCH",
                    ("BarrelStabilizer", "Buffs", "Force"),
                    ("AutomatonQueen", "Queen", "MinGauge"),
                    ("RookAutoturret", "Queen", "MinGauge"),
                    ("Wildfire", "WF", "ASAP"),
                    ("Detonator", "WF", "ASAP"),
                    ("Hypercharge", "Hypercharge", "Force"),
                    ("Drill", "Tools", "Automatic"),
                    ("HotShot", "Tools", "Automatic"),
                    ("AirAnchor", "Tools", "Automatic"),
                    ("ChainSaw", "Tools", "Automatic"),
                    ("Bioblaster", "Tools", "Automatic"))),

            ["Monk"] = CreateJobDefinition(
                "MNK",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassMNKUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("Mantra", "Mantra", "Use"),
                    ("RiddleOfEarth", "RiddleOfEarth", "Use"),
                    ("Thunderclap", "Thunderclap", "GapCloseHold2")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.MNK",
                    ("Brotherhood", "BH", "Force"),
                    ("RiddleOfFire", "RoF", "Force"),
                    ("FiresReply", "FiresReply", "Force"),
                    ("RiddleOfWind", "RoW", "Force"),
                    ("WindsReply", "WindsReply", "Force"),
                    ("PerfectBalance", "PB", "Force"),
                    ("ElixirField", "Blitz", "Automatic"),
                    ("FlintStrike", "Blitz", "Automatic"),
                    ("TornadoKick", "Blitz", "Automatic"),
                    ("ElixirBurst", "Blitz", "Automatic"),
                    ("RisingPhoenix", "Blitz", "Automatic"),
                    ("PhantomRush", "Blitz", "Automatic"),
                    ("SixSidedStar", "SixSidedStar", "Force"),
                    ("FormShift", "FormShift", "Force"),
                    ("SteeledMeditation", "Meditate", "Safe"),
                    ("ForbiddenMeditation", "Meditate", "Greedy"),
                    ("InspiritedMeditation", "Meditate", "Force"),
                    ("EnlightenedMeditation", "Meditate", "Delay"),
                    ("Thunderclap", "TC", "GapClose"),
                    ("TrueNorth", "TrueNorth", "Force"))),

            ["Ninja"] = CreateJobDefinition(
                "NIN",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassNINUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("ShadeShift", "Shade", "Use"),
                    ("Shukuchi", "Shukuchi", "GapCloseHold1")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.NIN",
                    ("Mug", "Buffs", "Force"),
                    ("Dokumori", "Buffs", "Force"),
                    ("ForkedRaiju", "ForkedRaiju", "Enabled"))),

            ["Paladin"] = CreateJobDefinition(
                "PLD",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassPLDUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Rampart", "Rampart", "Use"),
                    ("LowBlow", "LowBlow", "Use"),
                    ("Provoke", "Provoke", "Use"),
                    ("Interject", "Interject", "Use"),
                    ("Shirk", "Shirk", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Reprisal", "Reprisal", "UseEx"),
                    ("Cover", "Cover", "Use"),
                    ("Bulwark", "Bulwark", "Use"),
                    ("DivineVeil", "DivineVeil", "Use"),
                    ("HallowedGround", "HallowedGround", "Use"),
                    ("ShieldBash", "ShieldBash", "Use"),
                    ("Sheltron", "Sheltron", "Sheltron"),
                    ("HolySheltron", "Sheltron", "HolySheltron"),
                    ("Intervention", "Sheltron", "Intervention"),
                    ("Sentinel", "Sentinel", "Sentinel"),
                    ("Guardian", "Sentinel", "Guardian"),
                    ("PassageOfArms", "PassageOfArms", "CameraBackward")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.PLD",
                    ("FightOrFlight", "Buffs", "Force"),
                    ("Intervene", "Intervene", "Automatic"),
                    ("HolySpirit", "HS", "Force"),
                    ("Atonement", "Atone", "Automatic"),
                    ("Supplication", "Atone", "Delay"),
                    ("Sepulchre", "Atone", "Force"))),

            ["Pictomancer"] = CreateJobDefinition(
                "PCT",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassPCTUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Sleep", "Sleep", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Addle", "Addle", "UseEx"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("TemperaCoat", "Tempera Coat", "CoatGrassaWhenever"),
                    ("TemperaGrassa", "Tempera Coat", "CoatGrassaWhenever")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.PCT",
                    ("StarryMuse", "Buffs", "Force"),
                    ("StarrySkyMotif", "Buffs", "Force"),
                    ("MawMotif", "Motifs", "Instant"),
                    ("PomMotif", "Motifs", "Instant"),
                    ("ClawMotif", "Motifs", "Instant"),
                    ("WingMotif", "Motifs", "Instant"),
                    ("HammerMotif", "Motifs", "Instant"),
                    ("HolyInWhite", "Holy", "Force"),
                    ("CometInBlack", "Holy", "Force"),
                    ("HammerStamp", "Hammer", "Automatic"),
                    ("HammerBrush", "Hammer", "Delay"),
                    ("PolishingHammer", "Hammer", "Force"),
                    ("PomMuse", "Muse", "Force"),
                    ("WingedMuse", "Muse", "Force"),
                    ("ClawedMuse", "Muse", "Force"),
                    ("FangedMuse", "Muse", "Force"),
                    ("MogOfTheAges", "Portrait", "Force"),
                    ("RetributionOfTheMadeen", "Portrait", "Force"))),

            ["Reaper"] = CreateJobDefinition(
                "RPR",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassRPRUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("ArcaneCrest", "Crest", "Use")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.RPR",
                    ("ArcaneCircle", "Buffs", "Force"),
                    ("Enshroud", "Enshroud", "Force"),
                    ("Communio", "Communio", "Enabled"),
                    ("SoulSlice", "Slice", "Force"),
                    ("SoulScythe", "Slice", "Force"),
                    ("BloodStalk", "RedGauge", "Force"),
                    ("GrimSwathe", "RedGauge", "Force"),
                    ("Gluttony", "RedGauge", "ReserveGluttony"),
                    ("Gallows", "Reaver", "Automatic"),
                    ("Guillotine", "Reaver", "Automatic"),
                    ("ExecutionersGallows", "Reaver", "Automatic"),
                    ("ExecutionersGuillotine", "Reaver", "Automatic"),
                    ("Gibbet", "Reaver", "Automatic"),
                    ("ExecutionersGibbet", "Reaver", "Automatic"),
                    ("PlentifulHarvest", "PH", "Enabled"),
                    ("HarvestMoon", "HM", "Force"),
                    ("Perfectio", "Perf", "Automatic"),
                    ("Harpe", "Harpe", "Automatic"),
                    ("Soulsow", "Soulsow", "Enabled"),
                    ("ArcaneCrest", "Crest", "Enabled"))),

            ["Red Mage"] = CreateJobDefinition(
                "RDM",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassRDMUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Sleep", "Sleep", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Addle", "Addle", "UseEx"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("MagickBarrier", "Magick Barrier", "Use")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.RDM",
                    ("Embolden", "Buffs", "Force"),
                    ("Manafication", "Buffs", "Force"))),

            ["Sage"] = CreateJobDefinition(
                "SGE",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassSGEUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Repose", "Repose", "Use"),
                    ("Esuna", "Esuna", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Rescue", "Rescue", "Use"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("Eukrasia", "Eukrasia", "Use"),
                    ("Druochole", "Druochole", "Use"),
                    ("Kerachole", "Kerachole", "Use"),
                    ("Ixochole", "Ixochole", "Use"),
                    ("Pepsis", "Pepsis", "Use"),
                    ("Taurochole", "Taurochole", "Use"),
                    ("Haima", "Haima", "Use"),
                    ("Rhizomata", "Rhizomata", "Use"),
                    ("Holos", "Holos", "Use"),
                    ("Panhaima", "Panhaima", "Use"),
                    ("Krasis", "Krasis", "Use"),
                    ("Pneuma", "Pneuma", "Use"),
                    ("Philosophia", "Philosophia", "Use"),
                    ("Kardia", "Kardia", "Kardia"),
                    ("Soteria", "Kardia", "Soteria"),
                    ("Physis", "Physis", "Use"),
                    ("PhysisII", "Physis", "UseEx"),
                    ("Diagnosis", "Diagnosis", "Use"),
                    ("EukrasianDiagnosis", "Diagnosis", "UseED"),
                    ("Prognosis", "Prognosis", "Use"),
                    ("EukrasianPrognosis", "Prognosis", "UseEP"),
                    ("EukrasianPrognosisII", "Prognosis", "UseEPEx"),
                    ("Zoe", "Zoe", "UseEx"),
                    ("Icarus", "Icarus", "GapClose")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.SGE",
                    ("Phlegma", "Buffs", "Automatic"),
                    ("PhlegmaII", "Buffs", "Delay"),
                    ("PhlegmaIII", "Buffs", "Force"))),

            ["Samurai"] = CreateJobDefinition(
                "SAM",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassSAMUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("ThirdEye", "ThirdEye", "ThirdEye"),
                    ("Tengentsu", "ThirdEye", "Tengentsu")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.SAM",
                    ("Ikishoten", "Buffs", "Force"),
                    ("HissatsuSenei", "Buffs", "Force"),
                    ("Higanbana", "Higanbana", "Force"),
                    ("Enpi", "Enpi", "Ranged"),
                    ("MeikyoShisui", "Meikyo", "Force"))),

            ["Scholar"] = CreateJobDefinition(
                "SCH",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassSCHUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Repose", "Repose", "Use"),
                    ("Esuna", "Esuna", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Rescue", "Rescue", "Use"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("WhisperingDawn", "Whispering Dawn", "Use"),
                    ("Adloquium", "Adloquium", "Use"),
                    ("FeyIllumination", "Fey Illumination", "Use"),
                    ("Lustrate", "Lustrate", "Use"),
                    ("Indomitability", "Indomitability", "Use"),
                    ("EmergencyTactics", "EmergencyTactics", "Use"),
                    ("Dissipation", "Dissipation", "Use"),
                    ("Excogitation", "Excogitation", "Use"),
                    ("FeyBlessing", "FeyBlessing", "Use"),
                    ("Consolation", "Consolation", "Use"),
                    ("Protraction", "Protraction", "Use"),
                    ("Expedient", "Expedient", "Use"),
                    ("Seraphism", "Seraphism", "Use"),
                    ("SummonSeraph", "Seraph", "Use"),
                    ("Succor", "Succor", "Succor"),
                    ("Concitation", "Succor", "Concitation"),
                    ("SacredSoil", "Sacred Soil", "UseEx"),
                    ("DeploymentTactics", "DeploymentTactics", "UseEx"),
                    ("Aetherpact", "Aetherpact", "Use"),
                    ("DissolveUnion", "Aetherpact", "End"),
                    ("Recitation", "Recitation", "UseEx")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.SCH",
                    ("ChainStratagem", "Buffs", "Force"),
                    ("Dissipation", "Buffs", "Force"))),

            ["Summoner"] = CreateJobDefinition(
                "SMN",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassSMNUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Sleep", "Sleep", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Addle", "Addle", "UseEx"),
                    ("Swiftcast", "Swiftcast", "UseEx")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.SMN",
                    ("SearingLight", "Buffs", "Force"))),

            ["Viper"] = CreateJobDefinition(
                "VPR",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassVPRUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("SecondWind", "SecondWind", "Use"),
                    ("LegSweep", "LegSweep", "Use"),
                    ("Bloodbath", "Bloodbath", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Feint", "Feint", "UseEx"),
                    ("Slither", "Slither", "GapCloseHold2")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.VPR",
                    ("Reawaken", "Buffs", "Force"),
                    ("WrithingSnap", "WrithingSnap", "Ranged"))),

            ["Warrior"] = CreateJobDefinition(
                "WAR",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassWARUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Rampart", "Rampart", "Use"),
                    ("LowBlow", "LowBlow", "Use"),
                    ("Provoke", "Provoke", "Use"),
                    ("Interject", "Interject", "Use"),
                    ("Shirk", "Shirk", "Use"),
                    ("ArmsLength", "ArmsLength", "Use"),
                    ("Reprisal", "Reprisal", "UseEx"),
                    ("ThrillOfBattle", "ThrillOfBattle", "Use"),
                    ("Holmgang", "Holmgang", "Use"),
                    ("Equilibrium", "Equilibrium", "Use"),
                    ("ShakeItOff", "ShakeItOff", "Use"),
                    ("Vengeance", "Vengeance", "Vengeance"),
                    ("Damnation", "Vengeance", "Damnation"),
                    ("Bloodwhetting", "BW", "Bloodwhetting"),
                    ("RawIntuition", "BW", "RawIntuition"),
                    ("NascentFlash", "BW", "NascentFlash"))),

            ["White Mage"] = CreateJobDefinition(
                "WHM",
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.ClassWHMUtility",
                    ("Sprint", "Sprint", "Use"),
                    ("Repose", "Repose", "Use"),
                    ("Esuna", "Esuna", "Use"),
                    ("LucidDreaming", "LucidDreaming", "Use"),
                    ("Surecast", "Surecast", "Use"),
                    ("Rescue", "Rescue", "Use"),
                    ("Swiftcast", "Swiftcast", "UseEx"),
                    ("PresenceOfMind", "PresenceOfMind", "Use"),
                    ("Regen", "Regen", "Use"),
                    ("AfflatusSolace", "AfflatusSolace", "Use"),
                    ("AfflatusRapture", "AfflatusRapture", "Use"),
                    ("Benediction", "Benediction", "Use"),
                    ("ThinAir", "ThinAir", "Use"),
                    ("Tetragrammaton", "Tetragrammaton", "Use"),
                    ("DivineBenison", "DivineBenison", "Use"),
                    ("PlenaryIndulgence", "PlenaryIndulgence", "Use"),
                    ("Temperance", "Temperance", "Use"),
                    ("Aquaveil", "Aquaveil", "Use"),
                    ("DivineCaress", "DivineCaress", "Use"),
                    ("AetherialShift", "AetherialShift", "Use"),
                    ("Cure", "Cure", "Cure"),
                    ("CureII", "Cure", "CureII"),
                    ("CureIII", "Cure", "CureIII"),
                    ("MedicaII", "Medica", "MedicaII"),
                    ("MedicaIII", "Medica", "MedicaIII"),
                    ("Asylum", "Asylum", "Use"),
                    ("LiturgyOfTheBell", "LiturgyOfTheBell", "Use"),
                    ("LiturgyOfTheBellEnd", "LiturgyOfTheBell", "End")),
                CreateJobModuleDefinition(
                    "BossMod.Autorotation.xan.WHM",
                    ("PresenceOfMind", "Buffs", "Force"))),

        };
}
